### ISSUE TITLE
Request use nodejs/javascript

### ISSUE THREAD

**Issue by Mr4sR** [nsiregar/shpee#1]
Can u make like this but in nodejs / javascript ?

**Comment by nsiregar** [comment]
Sure

**Comment by Mr4sR** [comment]
> Sure

Is it done? if so where?

**Comment by nsiregar** [comment]
I create initial package here https://github.com/nsiregar/shpee-js 
Still unable to publish because wrong format previously

**Comment by nsiregar** [comment]
you can run npm install from git to install it, but it not cover all endpoint yet
```
https://github.com/nsiregar/shpee-js.git
```

**Comment by Mr4sR** [comment]
Oww ok thanks
